### ISSUE TITLE
MTT falsely reports success when app segfaults

### ISSUE THREAD

**Issue by rhc54** [open-mpi/mtt#668] opened 2018-07-10 22:40 UTC
If an application is marked as supposed to fail, then MTT returns "success" even if the app actually segfaults. This leads to a mistaken impression that the app ran correctly and returned the expected error status when in fact it crashed and burned.

**Comment by jsquyres** [comment] 2018-07-10 22:55
Is this with the Python client?

In the Cisco MTT Perl client, for "supposed to fail" failures, we should be checking both that the process exited (without signal) and that the exit status is nonzero.

**Comment by rhc54** [comment] 2018-07-10 22:57
No - it's with the Perl client.

**Comment by jsquyres** [comment] 2018-07-10 23:07
Is this with Cisco MTT results?

**Comment by rhc54** [comment] 2018-07-10 23:10
I encountered it while running MTT on my cluster - I happened to be watching the screen and saw a giant memory scram report go by, followed by "success". I then checked the MTT report from that run and found all tests had passed! Went back and dug into it to find that MTT was expecting test to "fail" and therefore reported success, but test had actually segfault'd.

**Comment by PeterGottesman** [comment] 2018-07-12 00:16
Yep, confirmed this is occurring on Cisco's MTT. I will take a look but I know nothing about perl so I probably can't help much past confirming it.
https://mtt.open-mpi.org/index.php?do_redir=2652

**Comment by rhc54** [comment] 2018-07-12 03:15
Let's first consider the segfault one. I believe that tests which fail "normally" exit with status of 1 (may be mangled to be 129) as that is what ORTE defaults to using. So we should be able to tell that one.

Will look more closely at the timeout case.

**Comment by jsquyres** [comment] 2018-07-12 15:36
But the definition of `simple_failures:pass = &and(&test_wifexited(), &ne(&test_wexitstatus(), 0))` *should* be sufficient -- i.e., `&test_wifexited()` should only return true if the process did not exit due to a signal (i.e., a segv).
Perhaps that's the real issue here: either 

1. `&test_wifexited()` is broken, and/or 
1. `WIFEXITED()` (per `wait(2)`) or its Perl equivalent *does* return True if a process exits via signal.

**Comment by rhc54** [comment] 2018-07-12 15:44
@jsquyres I am not sure what you are saying is correct. The problem is that mpirun itself did not exit due to segfault (which is what ```test_wifexited``` sees) - it is the application proc that did and all that happens is that mpirun returns a different status code

**Comment by jsquyres** [comment] 2018-07-12 16:06
Oh, I thought that's what you were reporting (that `mpirun` segv'ed).  I see now.

How well do we regular the `mpirun` exit statuses?  E.g., do we have a specific status for "killed the job because one of the processes died due to signal"?  (I know you cited 139 above, but I didn't know if that was a deliberate choice or if that's just the exit status that happened to be emitted)

**Comment by PeterGottesman** [comment] 2018-07-12 16:46
139 is a segfault, add the signal to 128 to get the signal's return code. On Linux syssegv is signal 11.
So, it seems like exit code of mpirun does reflect the fact that a process segfaulted.

**Comment by jsquyres** [comment] 2018-07-12 17:00
Ok.  We have a fairly homogeneous testing environment at Cisco, so if 128 is the magic offset (you might want to verify that by checking out exactly what `mpirun` returns -- hell, it might even be documented in `mpirun(1)`! 😉), that might be ok to hard-code in our `.ini` files.  Make sure to put in a good, detailed comment everywhere you do this explaining why that value is hard coded, ...etc.

Does the Python client have concepts like this?  I.e., I'm sure that some of the Perl sample `.ini` files use the same logic we do -- and it's probably not worth updating them.  Do any of the Python sample `.ini` files need to be updated with better logic?

**Comment by rhc54** [comment] 2018-07-12 17:51
I honestly don't know - @ribab ?

**Comment by PeterGottesman** [comment] 2018-07-19 00:22
@ribab I am sure the ini files themselves are fine, but do you know if MTT will fall to the same issue with WIFEXITED (or something similar if you are using a different mechanism)?
@jsquyres Sorry, this one got away from me. I will update our INIs and add a 4.0.x one before I leave the office today.
Let's not close this out until we know if it impacts the Python client too.

**Comment by ribab** [comment] 2018-07-20 17:14
@PeterGottesman @rhc54 I am not sure exactly what the issue is pertaining to the python client. The python client will exit on a nonzero status return code.

**Comment by rhc54** [comment] 2018-07-20 17:18
@ribab There are a lot of tests that are intended to report "failure" - i.e., they test conditions that _should_ result in a failure. These tests return a nonzero status code because they are supposed to do so. Thus, MTT gets instructed in the .ini file to treat a nonzero code as indicative of "success".

The issue in the Perl client is that a segfault in the application itself also causes mpirun to return a nonzero code. However, in that case the test didn't "succeed" as it didn't cleanly return the error. Instead, there is a significant problem in the code!

@PeterGottesman  is trying to resolve the problem for the Perl client - this was a "heads up" to you for the Python client.

**Closed** 2018-08-02 18:45 UTC
Labels: Perl Client
