### ISSUE TITLE
--duration timeout doesn't fail test

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#807] opened 2019-03-07 01:24 UTC
The `--duration` switch in MTT doesn't fail the test when the test exceeds duration timeout

For example

if `--duration 30` is set, then the test should timeout if it exceeds 30 seconds of runtime.

After 30 seconds, the test sees this

```
=======================================
KeyboardInterrupt exception was raised: <type 'exceptions.KeyboardInterrupt'> 
=======================================
```

This is because the watchdog plugin is implemented to cause a keyboard interrupt exception on expiration of watchdog timer.

However, MTT just ignores this exception.

I think MTT should be changed to not ignore this exception and fail on interrupt

**Comment by noahv** [comment] 2019-10-01 18:27
Closing this as not a bug.  The duration switch is designed to allow a test to loop or loop forever:

  --duration DURATION   Add a maximum duration for test before interrupting.
  --loop LOOP           Causes MTT to loop until provided number of seconds
                        finishes
  --loopforever         Causes MTT to continue to loop forever running same
                        set of tests

**Comment by noahv** [comment] 2019-10-01 18:28
If --watchdog is needed to error out a test runs too then a new enhancement will need to be filed.

We currently use SLURM timeouts and Jenkins timeouts for this behavior.

**Closed by noahv** 2019-10-01 18:29 UTC
Labels: Python Client, bug
